= Tests Generated from Unicode Files
:toc:

* Roast Test File
* Version number
* Date we last generated the file
* First two lines of the source file if the version is in the first line
   (`# NormalizationTest-10.0.0.txt`).
** If not (`# emoji-test.txt`) then include the line with the version number as well.

When regenerating, please add the first two lines of the source file,
as well as update the version and generation date.

== S15-nfg/mass-roundtrip-test-gen.p6
```
# NormalizationTest-11.0.0.txt
# Date: 2018-02-19, 18:33:08 GMT
```
* Regenerated 2018.10.01

.Test files:
* S15-nfg/mass-roundtrip-nfc.t
* S15-nfg/mass-roundtrip-nfd.t
* S15-nfg/mass-roundtrip-nfkc.t
* S15-nfg/mass-roundtrip-nfkd.t

NOTE: Tests generated were identical to the ones generated
     from 9.0/10.0/11.0
```
# NormalizationTest-10.0.0.txt
# Date: 2017-03-08, 08:41:55 GMT
```

== S15-nfg/emoji-test-gen.p6
* Emoji v11.0
* Regenerated 10-07-2018
* S15-nfg/emoji-test.t

```
# emoji-test.txt
# Date: 2018-02-07, 09:44:06 GMT
...
# Version: 11.0
```

```

== S15-nfg/mass-equality-gen.p6
* v9.0

== S32-str/CollationTestGen.p6
* v11.0

== S15-normalization/test-gen.p6
* v9.0

== S15-nfg/GraphemeBreakTest.t
* v11.0: 3rdparty/Unicode/11.0.0/ucd/auxiliary/GraphemeBreakTest.txt
